<a href="https://colab.research.google.com/github/MatthewFried/Udemy/blob/master/Foundation/_11%20Libraries_and_Review%20(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Review

In [ ]:
#if statement

x = int(input('Give me a number '))

if x <= 2 or x >6:
  print('Less than or equal to 2 or greater than 6')
elif x is 3:
  print('It is 3')
else:
  print('It is 4, 5, or 6')

Give me a number 3
It is 3


In [ ]:
#loops 

x = 5
while x < 10:
  print(x, end = " | ")
  x += 1

print()

for i in range(1,10):
  print(i, end = " --- ")

5 | 6 | 7 | 8 | 9 | 
1 --- 2 --- 3 --- 4 --- 5 --- 6 --- 7 --- 8 --- 9 --- 

In [ ]:
#functions

#function with defualt parameter
def square(number = 3):
  return number**2

x = 4
print(square(x))


#function that accepts multiple arguments
#returns multiple arguments
def arg(key, value):
  return key*2, value*2

k = 1
v = 10

#name which argument each input is
first, second = arg(key = k, value = v)
print(first, second)


#function that accepts any number of arguments
def average(*args):
  return sum(args)/len(args)

print(average(1,2,3,4,5,6))

#passing an individual element
grades = [88, 75, 96, 55, 83]
print(average(*grades))

16
2 20
3.5
79.4


In [ ]:
#random numbers

import random

for roll in range(10):
  print(random.randrange(1, 7), end=' ')

6 3 2 3 6 4 6 5 2 6 

In [ ]:
#lists
c = [5,'Mary', 3.4]
print(c[0])
print(c[-1])

5
3.4


In [ ]:
a_list = []
b_list = []

for number in range(1, 6):
  a_list += [number]
  b_list.append(number)

print(a_list)
print(b_list)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [ ]:
#slicing
numbers = [2, 3, 5, 7, 11, 13, 17, 19]
print(numbers[2:6])
print(numbers[:6])
print(numbers[6:])
print(numbers[::3])
print(numbers[::-1])

[5, 7, 11, 13]
[2, 3, 5, 7, 11, 13]
[17, 19]
[2, 7, 17]
[19, 17, 13, 11, 7, 5, 3, 2]


In [ ]:
#modify lists
numbers[1:3] = ['first','second']
print(numbers)

#puts 100 in every second spot
#uses 4*100 to make [100,100,100,100]
numbers[::2] = 4*[100]
print(numbers)

#delete from list using del
del numbers[0:2]
print(numbers)

[2, 'first', 'second', 7, 11, 13, 17, 19]
[100, 'first', 100, 7, 100, 13, 100, 19]
[100, 7, 100, 13, 100, 19]


In [ ]:
#sorting lists
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]

numbers.sort()
print(numbers)

numbers.sort(reverse=True)
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6,3,3,1]

print(100 in numbers)
print(3 not in numbers)

numbers.insert(1,'red')
print(numbers)

numbers.append('more')
print(numbers)

#extend to add all the elements of another sequence to the end of a list
numbers.extend(['indigo', 'violet'])
print(numbers)

#remove deletes the first element with a specified value
numbers.remove(9)
print(numbers)

#count searches for its argument and returns the number of times it is found
for i in range(1, 6):
  print(f'{i} appears {numbers.count(i)} times in responses')

#reverse the list elements
numbers.reverse()
print(numbers)

#copy a list
new_numbers = numbers.copy()
print("New numbers", new_numbers)

#clear the list
numbers.clear()
print(numbers)

False
False
[10, 'red', 3, 7, 1, 9, 4, 2, 8, 5, 6, 3, 3, 1]
[10, 'red', 3, 7, 1, 9, 4, 2, 8, 5, 6, 3, 3, 1, 'more']
[10, 'red', 3, 7, 1, 9, 4, 2, 8, 5, 6, 3, 3, 1, 'more', 'indigo', 'violet']
[10, 'red', 3, 7, 1, 4, 2, 8, 5, 6, 3, 3, 1, 'more', 'indigo', 'violet']
1 appears 2 times in responses
2 appears 1 times in responses
3 appears 3 times in responses
4 appears 1 times in responses
5 appears 1 times in responses
['violet', 'indigo', 'more', 1, 3, 3, 6, 5, 8, 2, 4, 1, 7, 3, 'red', 10]
New numbers ['violet', 'indigo', 'more', 1, 3, 3, 6, 5, 8, 2, 4, 1, 7, 3, 'red', 10]
[]


In [ ]:
#list comprehension
list2 = [item for item in range(1, 6)]
print(list2)

#operations in a list comprehension
list3 = [item ** 3 for item in range(1, 6)]
print(list3)

#filtering in a list comprehension
list4 = [item for item in range(1, 11) if item % 2 == 0]
print(list4)

#process one list comprehension with another


[1, 2, 3, 4, 5]
[1, 8, 27, 64, 125]
[2, 4, 6, 8, 10]


A **generator expression** is similar to a list comprehension, but creates an iterable generator object that produces values on demand. This is known as lazy evaluation. List comprehensions use greedy evaluation—they create lists immediately when you execute them. For large numbers of items, creating a list can take substantial memory and time. So generator expressions can reduce your program’s memory consumption and improve performance if the whole list is not needed at once.

Generator expressions have the same capabilities as list comprehensions, but you define them in parentheses instead of square brackets. 

In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
for value in (x ** 2 for x in numbers if x % 2 != 0):
  print(value, end=' ')

9 49 1 81 25 

###Filter, Map and Reduce

Python functions are objects that you can assign to variables, pass to other functions and return from functions. Functions that receive other functions as arguments are a functional-style capability called higher-order functions. For example, filter’s first argument must be a function that receives one argument and returns True if the value should be included in the result. The function is_odd returns True if its argument is odd. The filter function calls is_odd once for each value in its second argument’s iterable (numbers).

In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]

def is_odd(x):
 """Returns True only if x is odd."""
 return x % 2 != 0

k = list(filter(is_odd, numbers))
print(k)

[3, 7, 1, 9, 5]


In [ ]:
#usinga lambda as a simpler alternative
m = list(filter(lambda x: x % 2 != 0, numbers))
print(m)

[3, 7, 1, 9, 5]


In [ ]:
#mapping
n = list(map(lambda x: x ** 2, numbers))
print(n)

#the above is equivalent to
o = [item ** 2 for item in numbers]
print(o)

[100, 9, 49, 1, 81, 16, 4, 64, 25, 36]
[100, 9, 49, 1, 81, 16, 4, 64, 25, 36]


In [ ]:
#filter and map together
'''First, filter returns an iterable representing only the odd values of numbers. 
Then map returns an iterable representing the squares of the filtered values. 
Finally, list uses map’s iterable to create the list.'''

p = list(map(lambda x: x ** 2, filter(lambda x: x % 2 != 0, numbers)))
print(p)

#it is the same to do
[x ** 2 for x in numbers if x % 2 != 0]

[9, 49, 1, 81, 25]


[9, 49, 1, 81, 25]

###Zip

zip enables you to iterate over multiple iterables of data at the same time. The function receives as arguments any number of iterables and returns an iterator that produces tuples containing the elements at the same index in each. 

In [ ]:
names = ['Bob', 'Sue', 'Amanda']
grade_point_averages = [3.5, 4.0, 3.75]

for name, gpa in zip(names, grade_point_averages):
  print(f'Name={name}; GPA={gpa}')

Name=Bob; GPA=3.5
Name=Sue; GPA=4.0
Name=Amanda; GPA=3.75


###2D Lists



In [ ]:
#2D set up
a = [[77, 68, 86, 73], [96, 87, 89, 81], [70, 90, 86, 81]]
print(a)

print()

#iterate over the 2D list
for row in a:
  for item in row:
    print(item, end=' ')
  print()

[[77, 68, 86, 73], [96, 87, 89, 81], [70, 90, 86, 81]]

77 68 86 73 
96 87 89 81 
70 90 86 81 


##Numpy

In [ ]:
import numpy as np

numbers = np.array([2, 3, 5, 7, 11])
numbers2D = np.array([[1, 2, 3], [4, 5, 6]])

#show type
print(numbers.dtype)

#determine dimensions
print(numbers.shape)
print(numbers2D.shape)

#an array’s total number of elements with the attribute size
print("Numbers2D elements: ", numbers2D.size)

int64
(5,)
(2, 3)
Numbers2D elements:  6


In [ ]:
#iterate through multidimensional array
for row in numbers2D:
  for column in row:
    print(column, end=' ')
  print()

1 2 3 
4 5 6 


In [ ]:
#iterate after flattening
for i in numbers2D.flat:
  print(i, end=" ")

1 2 3 4 5 6 

In [ ]:
#filling arrays
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(4, 15)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(20,7,-3)

array([20, 17, 14, 11,  8])

In [ ]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#testing times
import random

%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

1 loop, best of 3: 5.81 s per loop
10 loops, best of 3: 63.8 ms per loop


In [ ]:
#numpy evaluations
grades = np.array([[87, 96, 70], [100, 87, 90],[94, 77, 90], [100, 81, 82]])

def stats(info):
  print(info.sum())
  print(info.min())
  print(info.max())
  print(info.mean())
  print(info.std())
  print(info.var())

stats(grades)



1054
70
100
87.83333333333333
8.792357792739987
77.30555555555556


In [ ]:
#row calculation
print(grades.std(axis = 0))

#column calculation
print(grades.std(axis=1))

[5.35607132 7.15454401 8.18535277]
[10.78064109  5.55777733  7.25718035  8.7305339 ]


In [ ]:
#slicing
print(grades)

print()

print("grades[1]\t", grades[1])
print()
print("grades[0:2]\n", grades[0:2])

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]

grades[1]	 [100  87  90]

grades[0:2]
 [[ 87  96  70]
 [100  87  90]]


In [ ]:
#print the first column
grades[:,0]

array([ 87, 100,  94, 100])

In [ ]:
#print the second and third columns
grades[:,1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [ ]:
#print column 0 and 2
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

###Flatten and Ravel

In [ ]:
#flatten the grades, this is a deep copy

flattened = grades.flatten()
print(flattened)

[ 87  96  70 100  87  90  94  77  90 100  81  82]


In [ ]:
#ravel produces a view of the original array, which shares the grades array’s data

raveled = grades.ravel()
print(raveled)

[ 87  96  70 100  87  90  94  77  90 100  81  82]


In [ ]:
#transpose data
grades.T

array([[ 87, 100,  94, 100],
       [ 96,  87,  77,  81],
       [ 70,  90,  90,  82]])

##Pandas

In [ ]:
import pandas as pd

grades = pd.Series([87, 100, 94])

#this has all the same .count(), .mean(), .min(), .max()
#use describe for all stats
print(grades.describe())


count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64


In [ ]:
#naming the index
#either approach is the same

grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Sam'])
grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})